repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        exclude: '.*(\.tox|venv|site-packages|\.?__pycache__|\.DS_Store|\.?_)'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.10
        exclude: '^.*(venv|\.DS_Store|\.AppleDouble|^\._).*$'