repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
        exclude: '.*\.tox/|.*venv/|.*site-packages/|.*\._.*\.py'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: ["--exclude=docs/"]
        language_version: python3.10
        exclude: '.*\.tox/|.*venv/|.*site-packages/|.*\._.*\.py'