site_name: Arkalia-LUNA Documentation
site_url: https://arkalia-luna-system.github.io/arkalia-luna-pro
repo_url: https://github.com/arkalia-luna-system/arkalia-luna-pro

theme:
  name: material
  logo: assets/logo.png            # ✅ Doit être dans docs/assets/
  favicon: assets/favicon.ico      # ✅ Doit être dans docs/assets/
  palette:
    - scheme: default
      primary: blue-grey           # 🌙 Bleu coton doux
      toggle:
        icon: material/weather-night
        name: Mode sombre
    - scheme: slate
      primary: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Mode clair
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arkalia-luna-system
  copyright:
    text: "© 2025 Arkalia System — Tous droits réservés."

nav:
  - 🧭 Accueil: index.md
  - 🧩 Modules: modules.md
  - ⚙️ API: api.md
  - 🧱 Structure: structure.md
  - 🧪 CI/CD: ci-cd.md
  - 🛣️ Roadmap: roadmap.md
  - 🧠 Kernel: kernel.md
  - 🛠️ Automatisation: automation.md
  - 📘 Crédits: credits.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.keys

extra_css:
  - assets/extra.css