{
  "timestamp": "2026-04-27T15:20:16.799984",
  "metrics": {
    "cpu": 23.8,
    "ram": 72.2,
    "latency": 1046.1,
    "containers": 0,
    "modules_active": 2,
    "errors": 0
  },
  "status": "degraded"
}