name: Arkalia CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .

    steps:
      - name: 🧾 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install \
            black \
            ruff \
            pytest \
            pytest-cov \
            pre-commit \
            mkdocs \
            mkdocs-material \
            mkdocs-simple-hooks \
            mkdocs-minify-plugin

      - name: 🌐 Construire le site MkDocs (sitemap.xml)
        run: |
          echo "::group::MkDocs Build"
          mkdocs build
          echo "::endgroup::"

      - name: 🧹 Lint avec Ruff
        run: |
          echo "::group::Ruff Lint"
          ruff check .
          echo "::endgroup::"

      - name: 🎨 Vérifier le format avec Black
        run: |
          echo "::group::Black Format Check"
          black . --check
          echo "::endgroup::"

      - name: 🧪 Lancer les tests unitaires avec couverture
        run: |
          echo "::group::Run Tests + Coverage"
          pytest --cov=modules --cov=core --cov=tests --cov-report=term-missing -v --tb=short
          echo "::endgroup::"

      - name: ✅ Exécuter les hooks pre-commit
        run: |
          echo "::group::Pre-commit Checks"
          pre-commit run --all-files --show-diff-on-failure
          echo "::endgroup::"